export const LOG_EVENTS = [
  'system.boot',
  'system.shutdown',
  'http.request.received',
  'http.request.handled',
  'http.request.error',
  'agent.created',
  'agent.updated',
  'agent.deleted',
  'agent.paused',
  'agent.resumed',
  'agent.run.started',
  'agent.run.config_loaded',
  'agent.run.spend_reserved',
  'agent.run.spend_rejected',
  'agent.run.secret_fetched',
  'agent.run.anthropic_call',
  'agent.run.anthropic_response',
  'agent.run.spend_finalized',
  'agent.run.spend_refunded',
  'agent.run.spend_refund_failed',
  'agent.run.persisted',
  'agent.run.completed',
  'agent.run.failed',
  'schedule.upserted',
  'schedule.removed',
  'sandbox.run.sync_down',
  'sandbox.run.flush',
  'sandbox.run.app_exited',
  'sandbox.run.sync_up',
] as const;

export type LogEvent = (typeof LOG_EVENTS)[number];
