export const LOG_EVENTS = [
  'system.boot',
  'system.shutdown',
  'http.request.received',
  'http.request.handled',
  'http.request.error',
  'agent.created',
  'agent.updated',
  'agent.deleted',
  'agent.paused',
  'agent.resumed',
  'agent.run.started',
  'agent.run.config_loaded',
  'agent.run.spend_reserved',
  'agent.run.spend_rejected',
  'agent.run.secret_fetched',
  'agent.run.anthropic_call',
  'agent.run.anthropic_response',
  'agent.run.spend_finalized',
  'agent.run.persisted',
  'agent.run.completed',
  'agent.run.failed',
  'schedule.upserted',
  'schedule.removed',
  'sandbox.run.sync_down',
  'sandbox.run.flush',
  'sandbox.run.app_exited',
  'sandbox.run.sync_up',
  // Launcher + lifecycle events (emitted by the runner/lifecycle Lambdas):
  'sandbox.run.launched',
  'sandbox.run.launch_failed',
  'sandbox.run.finalized',
  'sandbox.run.grants_injected',
  'sandbox.run.grant_denied',
  // Egress-proxy sidecar events (emitted by the per-run proxy container):
  'sandbox.proxy.started',
  'sandbox.egress.allowed',
  'sandbox.egress.denied',
] as const;

export type LogEvent = (typeof LOG_EVENTS)[number];
